--SEKVENCE

 

CREATE SEQUENCE "PRODAJNO_MESTO_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;



CREATE SEQUENCE "LEK_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 200 CACHE 20 NOORDER CYCLE;

 


CREATE SEQUENCE "BOLEST_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER CYCLE;

 


CREATE SEQUENCE "PROIZVOĐAČ_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER CYCLE;

 

CREATE SEQUENCE "RECEPT_SERIJSKI_BROJ_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER CYCLE;

 

CREATE SEQUENCE "VRSTA_PAKOVANJA_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER CYCLE;

 

CREATE SEQUENCE "RADIU_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER CYCLE;

 

CREATE SEQUENCE "SENALAZI_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER CYCLE;

 

CREATE SEQUENCE "LEČI_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER CYCLE;

 









CREATE TABLE PRODAJNO_MESTO(
ID NUMBER(13),
NAZIV VARCHAR(20) NOT NULL,
ULICA VARCHAR(20) NOT NULL,
BROJ NUMBER(7) NOT NULL,
GRAD VARCHAR(20) NOT NULL

);

ALTER TABLE PRODAJNO_MESTO ADD PRIMARY KEY(ID);

CREATE TABLE ZAPOSLENI(
JMBG NUMBER(13),
IME VARCHAR(20) NOT NULL,
PREZIME VARCHAR(20) NOT NULL,
ULICA VARCHAR(20) NOT NULL,
BROJ NUMBER(7) NOT NULL,
GRAD VARCHAR(20) NOT NULL,
datum_rođenja DATE NOT NULL,
PRODMESTOID NUMBER(13)
);

ALTER TABLE ZAPOSLENI ADD PRIMARY KEY(JMBG);
ALTER TABLE ZAPOSLENI ADD CONSTRAINT PRODMESTOID_FK FOREIGN KEY(PRODMESTOID) REFERENCES PRODAJNO_MESTO(ID) ENABLE;


CREATE TABLE FARMACEUT(
JMBG NUMBER(13),
DATUM_DIPLOMIRANJA DATE NOT NULL,
DATUM_OBNOVE_LICENCE DATE NOT NULL
);

ALTER TABLE FARMACEUT ADD PRIMARY_KEY(JMBG);


CREATE TABLE PROIZVOĐAČ(
ID NUMBER(13),
NAZIV VARCHAR(20) NOT NULL
);

ALTER TABLE PROIZVOĐAČ ADD PRIMARY KEY(ID);

CREATE TABLE LEKAR(
ŠIFRA NUMBER(10),
IME VARCHAR(20) NOT NULL,
PREZIME VARCHAR(20) NOT NULL,
BROJ_TELEFONA NUMBER(10) NOT NULL
);

ALTER TABLE LEKAR ADD PRIMARY KEY(ŠIFRA);

CREATE TABLE BOLEST(
ID NUMBER(13),
NAZIV VARCHAR(20) NOT NULL
);

ALTER TABLE BOLEST ADD PRIMARY KEY(ID);

CREATE TABLE PRIMARNA_GRUPA(
NAZIV VARCHAR(13)
);

ALTER TABLA PRIMARNA_GRUPA ADD PRIMARY KEY(NAZIV);
ALTER TABLE PRIMARNA_GRUPA ADD CONSTRAINT NAZIV_CHK CHECK (NAZIV IN ('antibiotik','analgetik','antipiretik','diuretik'));

CREATE TABLE LEK(
ID NUMBER(13),
KOMERCIJALNI_NAZIV VARCHAR(20) NOT NULL,
HEMIJSKI_NAZIV VARCHAR(20) NOT NULL,
CENA NUMBER(7) NOT NULL,
DOZA_TRUDNICE NUMBER(7) NOT NULL,
DOZA_DECA NUMBER(7) NOT NULL,
DOZA_ODRASLI NUMBER(7) NOT NULL,
IDPROIZVOĐAČA NUMBER(13),
NAZIVPRIMGRUPE VARCHAR(13)


);

ALTER TABLE LEK ADD PRIMARY KEY(ID);
ALTER TABLE LEK ADD CONSTRAINT IDPROIZVOĐAČA_FK FOREIGN KEY(IDPROIZVOĐAČA) REFERENCES PROIZVOĐAČ(ID) ENABLE;
ALTER TABLE LEK ADD CONSTRAINT NAZIVPRIMGRUPE_FK FOREIGN KEY(NAZIVPRIMGRUPE) REFERENCES PRIMARNA_GRUPA(NAZIV) ENABLE;


------------------------------------------
CREATE TABLE RECEPT(
SERIJSKI_BROJ NUMBER(10),
ŠIFRALEKARA NUMBER(10) NOT NULL,
PRODMESTOID NUMBER(13) NOT NULL,
JMBGZAPOSLENOG NUMBER(13) NOT NULL
);

ALTER TABLE RECEPT ADD PRIMARY KEY(SERIJSKI_BROJ);
ALTER TABLE RECEPT ADD CONSTRAINT ŠIFRALEKARA_FK FOREIGN KEY(ŠIFRALEKARA) REFERENCES LEKAR(ŠIFRA);
ALTER TABLE RECEPT ADD CONSTRAINT PRODMESTOID_FK FOREIGN KEY(PRODMESTOID) REFERENCES PRODAJNO_MESTO(ID);
ALTER TABLE RECEPT ADD CONSTRAINT JMBGZAPOSLENOG_FK FOREIGN KEY(JMBGZAPOSLENOG) REFERENCES ZAPOSLENI(JMBG);

--------------------------



CREATE TABLE VRSTA_PAKOVANJA (
ID NUMBER(13),
TIP VARCHAR(15) NOT NULL

);
ALTER TABLE VRSTA_PAKOVANJA ADD PRIMARY KEY(ID);
ALTER TABLE VRSTA_PAKOVANJA ADD CONSTRAINT TIP_CHK CHECK (TIP IN ('injekcija','prašak','tablete','sirup'));

CREATE TABLE LEK_ZA_PRODAJU(
ID NUMBER(13) 
);

ALTER TABLE LEK_ZA_PRODAJU ADD CONSTRAINT "LEK_ZA_PRODAJU_PK" PRIMARY KEY("ID");

CREATE TABLE LEK_ZA_IZDAVANJE(
ID NUMBER(13),
PROCENAT_PARTICIPACIJE NUMBER(10) NOT NULL
); 

ALTER TABLE LEK_ZA_IZDAVANJE ADD CONSTRAINT "LEK_ZA_IZDAVANJE_PK" PRIMARY KEY("ID");

CREATE TABLE SE_NALAZI(
PRODMESTOID NUMBER(13),
LEKID NUMBER(13),
KOLIČINA NUMBER(13) NOT NULL
);

ALTER TABLE SE_NALAZI ADD CONSTRAINT "SE_NALAZI_PK" PRIMARY KEY("PRODMESTOID", "LEKID");
ALTER TABLE SE_NALAZI ADD CONSTRAINT "SE_NALAZI_PRODAJNO_MESTO_FK" FOREIGN KEY("PRODMESTOID") REFERENCES PRODAJNO_MESTO("ID");
ALTER TABLE SE_NALAZI ADD CONSTRAINT "SE_NALAZI_LEK_FK" FOREIGN KEY("LEKID") REFERENCES LEK("ID");

CREATE TABLE SE_PAKUJE(
LEKID NUMBER(13),
PAKOVANJEID NUMBER(13),
SASTAV VARCHAR(240) NOT NULL,
KOLIČINA NUMBER(20) NOT NULL
);

ALTER TABLE SE_PAKUJE ADD CONSTRAINT "SE_PAKUJE_PK" PRIMARY KEY("LEKID","PAKOVANJEID");
ALTER TABLE SE_PAKUJE ADD CONSTRAINT "SE_PAKUJE_LEK_FK" FOREIGN KEY("LEKID") REFERENCES LEK("ID");
ALTER TABLE SE_PAKUJE ADD CONSTRAINT "SE_PAKUJE_PAKOVANJE_FK" FOREIGN KEY("PAKOVANJEID") REFERENCES VRSTA_PAKOVANJA("ID");

CREATE TABLE LEČI(
LEKID NUMBER(13),
BOLESTID NUMBER(13)
);

ALTER TABLE LEČI ADD CONSTRAINT "LEČI_PK" PRIMARY KEY("LEKID","BOLESTID");
ALTER TABLE LEČI ADD CONSTRAINT "LEČI_LEK_FK" FOREIGN KEY("LEKID") REFERENCES LEK("ID");
ALTER TABLE LEČI ADD CONSTRAINT "LEČI_BOLEST_FK" FOREIGN KEY("BOLESTID") REFERENCES BOLEST("ID");

CREATE TABLE PREPISAN(
LEKID NUMBER(13),
SERBR NUMBER(10),
KOLIČINA VARCHAR(100) NOT NULL
);

ALTER TABLE PREPISAN ADD CONSTRAINT "PREPISAN_PK" PRIMARY KEY("LEKID","SERBR");
ALTER TABLE PREPISAN ADD CONSTRAINT "PREPISAN_LEK_FK" FOREIGN KEY("LEKID") REFERENCES LEK("ID");
ALTER TABLE PREPISAN ADD CONSTRAINT "PREPISAN_RECEPT_FK" FOREIGN KEY("SERBR") REFERENCES RECEPT("SERIJSKI_BROJ");

CREATE TABLE SADRŽI_TIP(
SERBR NUMBER(10), 
NAZIVPRIMGRUPE NUMBER(10)
);

ALTER TABLE SADRŽI_TIP ADD CONSTRAINT "SADRŽI_TIP_PK" PRIMARY KEY("SERBR","NAZIVPRIMGRUPE");
ALTER TABLE SADRŽI_TIP ADD CONSTRAINT "SADRŽI_TIP_RECEPT_FK" FOREIGN KEY("SERBR") REFERENCES RECEPT("SERIJSKI_BROJ");
ALTER TABLE SADRŽI_TIP ADD CONSTRAINT "SADRŽI_TIP_PRIMGRUPA_FK" FOREIGN KEY("NAZIVPRIMGRUPE") REFERENCES PRIMARNA_GRUPA("NAZIV");

CREATE TABLE SADRŽI_VRSTU(
SERBR NUMBER(10),
VRSTAID NUMBER(13)
);


ALTER TABLE SADRŽI_VRSTU ADD CONSTRAINT "SADRŽI_VRSTU_PK" PRIMARY KEY("SERBR","VRSTAID");
ALTER TABLE SADRŽI_VRSTU ADD CONSTRAINT "SADRŽI_VRSTU_RECEPT_FK" FOREIGN KEY("SERBR") REFERENCES RECEPT("SERIJSKI_BROJ");
ALTER TABLE SADRŽI_VRSTU ADD CONSTRAINT "SADRŽI_VRSTU_VRSTA_FK" FOREIGN KEY("VRSTAID") REFERENCES VRSTA_PAKOVANJA("ID");

CREATE TABLE LEK_KONTRAINDIKACIJE(
LEKID NUMBER(13),
KONTRAINDIKACIJE VARCHAR(200) 
);

ALTER TABLE LEK_KONTRAINDIKACIJE ADD CONSTRAINT "LEK_KONTRAINDIKACIJE_PK" PRIMARY KEY("LEKID","KONTRAINDIKACIJE");
ALTER TABLE LEK_KONTRAINDIKACIJE ADD CONSTRAINT "LEK_KONTRAINDIKACIJE_FK" FOREIGN KEY("LEKID") REFERENCES LEK("ID");

CREATE TABLE LEK_NEŽELJENI_EFEKTI(
LEKID NUMBER(13),
NEŽELJENI_EFEKTI VARCHAR(200) 
);

ALTER TABLE LEK_NEŽELJENI_EFEKTI ADD CONSTRAINT "LEK_NEŽELJENI_EFEKTI_PK" PRIMARY KEY("LEKID","NEŽELJENI_EFEKTI");
ALTER TABLE LEK_NEŽELJENI_EFEKTI ADD CONSTRAINT "LEK_NEŽELJENI_EFEKTI_FK" FOREIGN KEY("LEKID") REFERENCES LEK("ID");

CREATE TABLE ZAPOSLENI_BRTEL(
JMBGZAPOSLENOG NUMBER(13),
BROJ_TELEFONA NUMBER(10) 
);

ALTER TABLE ZAPOSLENI_BRTEL ADD CONSTRAINT "ZAPOSLENI_BRTEL_PK" PRIMARY KEY("JMBGZAPOSLENOG","BROJ_TELEFONA");
ALTER TABLE ZAPOSLENI_BRTEL ADD CONSTRAINT "ZAPOSLENI_BRTEL_FK" FOREIGN KEY("JMBGZAPOSLENOG") REFERENCES ZAPOSLENI("JMBG");


--TRIGGERI
 

CREATE OR REPLACE TRIGGER "PRODAJNO_MESTO_AUTO_PK"
BEFORE INSERT
    ON PRODAJNO_MESTO
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT PRODAJNO_MESTO_ID_SEQ.NEXTVAL INTO:NEW.ID FROM DUAL;
END;



 

CREATE OR REPLACE TRIGGER "LEK_AUTO_PK"
BEFORE INSERT
    ON LEK
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT LEK_ID_SEQ.NEXTVAL INTO:NEW.ID FROM DUAL;
END;



 


CREATE OR REPLACE TRIGGER "RECEPT_AUTO_PK"
BEFORE INSERT
    ON RECEPT
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT RECEPT_SERIJSKI_BROJ_SEQ.NEXTVAL INTO:NEW.SERIJSKI_BROJ FROM DUAL;
END;





 

CREATE OR REPLACE TRIGGER "VRSTA_PAKOVANJA_AUTO_PK"
BEFORE INSERT
    ON VRSTA_PAKOVANJA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT VRSTA_PAKOVANJA_ID_SEQ.NEXTVAL INTO:NEW.ID FROM DUAL;
END;





